name = "Blosc"
uuid = "a74b3585-a348-5f62-a45c-50e91977d574"
version = "0.7.3"

[deps]
Blosc_jll = "0b7ba130-8d10-5ba8-a3d6-c5182647fed9"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
